name: Validate

on:
  push:
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  hacs:
    runs-on: ubuntu-latest
    name: HACS
    steps:
      - name: HACS validation
        uses: hacs/action@main
        with:
          category: integration
